### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by buso** [corex/kanboard-crproject#1]
I downloaded the plugin and copied it to the Plugins folder with the name CRProject as per the instructions.  When I refresh my Kanboard site, i get error: ERR_TOO_MANY_REDIRECTS.  I am running Kanboard 1.2.9 with IIS server 8.5 in Windows Server 2012.

**Comment by corex** [comment]
O.O I was not aware that anyone used this plugin. I will look into the codebase as soon as possible. However, I am not running Windows Server, so I might not be able to reproduce it.

**Comment by corex** [comment]
I am not able to reproduce this but I have a theory of what caused it. This should be fixed now. 1.2.1 released.

**Comment by buso** [comment]
Thanks for working on this.  I had abandoned the plugin as I couldn't get
it to work, but I will give it a try again and let you know if the fix
worked.

**Comment by corex** [comment]
Honestly, I was not aware that anyone used this plugin. It was primarily built for myself since I have many smaller projects and I need to have a good view of them. I will start working on a new version that will document the features.

I think the problem you experienced was due to bad schema combined with a redirect for "plugin project board". This has been changed to work only when ENABLE_URL_REWRITE is set to true in config.

**Comment by corex** [comment]
Just released version 1.2.2 with updated documentation.
